# Generated by Django 5.1 on 2024-09-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversaciones', '0006_rename_usuario_conversacion_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversacion',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
